apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      app: jenkins-test
    spec:
      containers:
      - name: test
        image: payaljain/jenkins-test:1
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-service
spec:
  type: LoadBalancer
  selector:
    app: jenkins-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
